# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  pkgs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [];
    };
    kernelModules = [
      "kvm-intel"
    ];
    extraModulePackages = [];
    kernel.sysctl."vm.swappiness" = 100;
  };

  # The Intel N150 (Alder Lake-N generation) embedded in the Beelink S13 is an
  # excellent low-power chip for a homelab, but its 4 cores / 4 threads and
  # non-expandable 16 GB of RAM require a few sensible optimizations. With
  # your 1 TB NVMe SSD and RAM-based architecture, the goal is to maximize CPU
  # responsiveness, save RAM for your future containers, and preserve the SSD's
  # lifespan.
  #
  # 1. RAM Optimization (ZRAM vs. TMPFS)
  # Since your OS already runs in RAM via tmpfs, you need to prevent memory
  # starvation if you deploy many containers. Instead of creating a traditional
  # Swap partition on the SSD (which would wear it out prematurely), we enable
  # ZRAM to create a compressed swap space directly inside your RAM. The Intel
  # N150 processor is more than fast enough to handle on-the-fly compression and
  # decompression. This virtually "expands" your memory (16 GB of physical RAM
  # can behave like ~24 GB of usable space).
  #
  # Enable compressed swap in RAM.
  zramSwap = {
    enable = true;
    algorithm = "zstd"; # Best compression/speed ratio for the Intel N150.
    memoryPercent = 50; # Use up to 50% of max RAM for the compressed swap.
  };
  #
  # Adjust the kernel's tendency to swap (swappiness)
  # We tell it to aggressively swap into ZRAM to free up "real" RAM for apps.
  # (Note: moved inside boot block at the top of the file to prevent repeated boot attributes warnings)
  #
  # 2. Intel Microcode and Power Management
  # The N150 is a modern processor architecture composed entirely of "E"
  # (efficiency) cores. For it to properly manage its frequencies and sleep
  # states (especially for a headless server running 24/7), it needs up-to-date
  # microcode and an appropriate governor.
  #
  # Update Intel microcode (crucial for N150 stability and security).
  hardware.cpu.intel.updateMicrocode = true;
  #
  # Optimize power management for a headless server.
  powerManagement.cpuFreqGovernor = "schedutil"; # Perfect balance between responsiveness and power saving.
  #
  # Optional: Load Intel iGPU graphics drivers (Intel UHD Graphics), highly
  # useful if you later do Plex/Jellyfin hardware video transcoding or object
  # detection.
  hardware.graphics = {
    enable = true;
    extraPackages = [
      pkgs.intel-media-driver # For QuickSync hardware transcoding
      pkgs.intel-compute-runtime # For OpenCL / lightweight AI
    ];
  };
  #
  # 3. Preservation and Performance of the 1 TB NVMe SSD
  # The Beelink S13 uses an NVMe SSD. To prevent it from slowing down over time
  # (due to block write wear) and to ensure Btrfs doesn't write unnecessarily,
  # we enable the weekly TRIM service and adjust the mount options in `disko.nix`.
  #
  # Enable weekly TRIM to maintain the performance of the 1 TB SSD
  services.fstrim.enable = true;
  services.fstrim.interval = "weekly";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
