_: {
  # Cloudflare Tunnel configuration for CouchDB exposure.
  # The mapping between couchdb.vaylet.fr and this local instance
  # is managed via the Cloudflare Zero Trust dashboard.
  services.cloudflared = {
    enable = true;
    tunnels = {
      "1ee69e49-d8a2-44e9-94bf-8e45b819e5f9" = {
        # Credentials file generated by `cloudflared` CLI.
        # It must be kept secure and stored in a persistent directory.
        credentialsFile = "/var/lib/cloudflare-tunnel/1ee69e49-d8a2-44e9-94bf-8e45b819e5f9.json";

        # Default route pointing to Caddy, which then proxies to CouchDB.
        default = "http://127.0.0.1:80";
      };
    };
  };
}
